apiVersion: v1
kind: Service
metadata:
  name: service-grafana
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          imagePullPolicy: Never
          image: deployment-grafana
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "100Mi"
              cpu: "70m"